### PR TITLE
#231: Add `dry_run` and optional `overwrite` to sampling workflow

### LINKED ISSUE #231: Add dry_run and optional overwrite to sampling workflow
For the sampling workflow, it would be nice to have an opportunity to do a "dry run" where we just initialize all the directories w/o actually running the model. 

It would additionally be nice to have an "overwrite" option, where, before we run a model, we identify if a model has successfully been run in this location. If we have an overwrite flag set to false, we will pass over running this model.

### PR DESCRIPTION
**Pull request by cwschilly**
Fixes #231

This PR adds and tests these arguments to `run_sampling`:
- [x] `dry_run`
- [x] `overwrite`

### CODE REVIEW

**Comment by cwschilly** [comment]
@eparish1 This PR is ready for review

I implemented the `overwrite` slightly different than you suggested [here](https://github.com/Pressio/rom-tools-and-workflows/issues/231#issuecomment-2329362458)--instead of writing `passed.txt` after every sample, I write it out once to the `absolute_sampling_directory` after all samples have been run successfully.

**Review by fnrizzi — APPROVED** [review]

**Review by eparish1 — CHANGES_REQUESTED** [review]
@cwschilly  The dry run looks great, thanks! For the overwrite, I would like this to work on a per-sample basis, rather than for the whole sampling workflow. The idea would be if, say, your computer crashes after sample 14, you don't have to. So could we:

1.) add the "passed" logic to work on a per run basis (e.g., we could add it to the run_sample snippet)
2.) As we loop through our samples, check for the passed file in each sample?

**Comment by fnrizzi** [comment]
@cwschilly needs rebasing

**Review by eparish1 — APPROVED** [review]
This is great, thanks!!!

**Pull request merged**
