### PR TITLE
get rid of get_dimension() usage since that got renamed

### PR DESCRIPTION
**Pull request by jtencer**

### CODE REVIEW

**Comment by eparish1** [comment]
@jtencer Thanks for catching this. Could we add a test or two to outputter?

**Comment by jtencer** [comment]
The problem with adding a test that covers the exodus outputter is that it adds an extra dependency that we don't currently build with (seacas).  I can add tests for the other 2 though and as of now they all depend on the same aspects of the `vector_space` api.

**Comment by jtencer** [comment]
ultimately, we might want to move the exodus one to the aria repo instead but we've been kicking that can down the road

**Comment by eparish1** [comment]
Agree on both comments. I just didn't catch the get_dimension in this because we didn't have a test; I think everything else is covered so might as well add a basic thing for h5py and npz to just make sure the functions work.

**Comment by jtencer** [comment]
@eparish1 I added tests for npz and hdf5 output

**Review by fnrizzi — APPROVED** [review]

**Pull request merged**
