### PR TITLE
updated sampler to use model

### PR DESCRIPTION
**Pull request by eparish1**

### CODE REVIEW

**Comment by fnrizzi** [comment]
all the CI is failing, is this expected because this is wip or this is done and CI should not fail?

**Comment by eparish1** [comment]
@fnrizzi I'm working on fixing it, the fail didn't happen on my machine.

**Comment by fnrizzi** [comment]
ok ready, i will check!

**Review by fnrizzi — APPROVED** [review]

**Comment by fnrizzi** [comment]
all tests pass so i am good

**Pull request merged**
