### PR TITLE
#115: Update shifter API and implementations

### LINKED ISSUE #115: Update shifter API and implementations
Update shifter API as:
```
class <SomeShifter>(Shifter):

    def apply_shift(self,my_array: np.ndarray):
       ## apply shift to input array in place

    def remove_shift(self,my_array: np.ndarray):
       ## undo shift vector in place 
```

Additionally, all operations should be made to be in place in the shifter class. Tests should check for this.

### LINKED ISSUE #131: ConstantShifter should accept a number
ConstantShifter currently accepts a numpy array of values (one for each variable).  This is fine, but for cases in which there is only one variable or when all variables should be shifted by the same value, it is unnecessary and confusing.  ConstantShifter should also accept a number in those cases and should not result in an error when passed a number.

### PR DESCRIPTION
**Pull request by cwschilly**
Fixes #115
Fixes #131

### CODE REVIEW

**Comment by cwschilly** [comment]
@eparish1 @fnrizzi 

I implemented the `remove_shift` function by simply returning the original matrix passed to `apply_shift`.

The alternative would be to actually perform the inverse of the shift. I thought returning the original matrix was simpler, but if the other way makes more sense for the intended uses for this class, let me know!

**Review by eparish1 — CHANGES_REQUESTED** [review]
@cwschilly Thanks! A few requested changes:

1. Can we change remove_shift to apply_inverse_shift 
2. Can we make both apply_shift and apply_inverse_shift act in place on the input matrices? (e.g., input_matrix -= shift). The reason is that apply_shift and apply_inverse_shift are acting on really big matrices so probably best not to duplicate it.
3. Let's then have apply_shift and apply_inverse_shift not return anything since they act in place

With these changes, the remove_shift will have to actually perform the inverse shift (which probably makes the most sense for the downstream applications).

Thanks! Let me know if anything isn't clear.

**Comment by cwschilly** [comment]
Hi @eparish1 

Is the primary goal of `apply_inverse_shift` to...
1. return the original matrix (ie you would call this after calling `apply_shift`), or
2. simply shift a matrix in the opposite direction as `apply_shift`?

This is only relevant for `FirstVecShifter` and `AverageShifter`, since their shift_vectors are based on their input matrix. (The other shifters have pre-set shift_vectors and so this isn't an issue--the inverse function accomplishes both of the above points.)

If the the output of `apply` becomes the input to `inverse` (with the intent of returning the original matrix), then I would save the original shift vector from `apply` and use that.

Alternatively, if the intent is just to shift in the opposite direction, then I would generate the shift vector directly from the input to `inverse`. In this case, the output from the `inverse` will not match the original matrix passed to `apply_shift`.

**Comment by eparish1** [comment]
@cwschilly Good question:

-  "apply_inverse_shift" could be used to do both use cases you mentioned, with the latter probably being more used. 
- However, when doing the "inverse" shift, it should still use the shift vector derived from the forward shift (nothing should be derived from the matrix input to inverse shift. 
- This makes me think that maybe we don't have the best API for the FirstVecShifter and AverageShifter, which derive the shift vecs from the input apply shift. I propose for these implementations we move the construction of the shift vec to the constructor, and have the snapshot_tensor be an input that is passed to the constructor.

@cwschilly @fnrizzi @jtencer  @pjb236  what do you think?

**Comment by jtencer** [comment]
I don't love needing the snapshot tensor in hand when the constructor is called.

**Comment by pjb236** [comment]
Maybe we just implement helper functions to compute the average of a snapshot matrix or to select a snapshot. I feel like these are the two main options for a shift, aside from zero

**Comment by eparish1** [comment]
@jtencer Would requiring the snapshots for construction break any of your workflows? I didn't originally like it, but the more I think about it I don't know if I see an issue since we need the snapshots to compute the trial space. We could also have a non-constructor set_shift() or something that gets called first?

**Comment by jtencer** [comment]
I don't think it would break any of my workflows, it just feels a little clunky to provide the snapshot tensor twice.  I don't really have a good way around it that doesn't involve introducing a weird statedness to the class though.

**Comment by eparish1** [comment]
@pjb236 @fnrizzi Can you please share thoughts on this one?

**Comment by fnrizzi** [comment]
> @pjb236 @fnrizzi Can you please share thoughts on this one?

yeah looking now

**Comment by fnrizzi** [comment]
i dont think we have a lof wiggle room tbh. and I don't think we should construct a shifter by passing a matrix. 
I think `AverageShifter` and `FirstVecShifter` are both kind of syntactic sugar for the same thing. 
IMO we should have: 
- a shifter that shifts by a generic vector and its constructor takes only the vector to use for shifting 

- a free function `extract_first_vector` that accepts a matrix and returns a copy of the first vector whcih can be used to construct the shfiter 

- a similar free function `extract_average_vector` 
etc. 

if we do this, we only need to extend other functions without changing the shifter class

**Comment by jtencer** [comment]
So in that case, we would have something like

`my_shifter = VectorShifter(vector = extract_first_vector(snapshots))`?

I think I'm OK with that although not 100% on the usage of "vector"

The alternative would be to have the `FirstVecShifter` class inherit from `VectorShifter`, something like:

```
class FirstVecShifter(VectorShifter):
    def __init__(self, snapshot_tensor):
        first_vec = extract_first_vector(snapshot_tensor)
        super().__init__(vector=first_vec)
```
and then the call is just
`my_shifter = FirstVecShifter(snapshots)`

I think you're probably splitting hairs at that point because both are really doing the same thing.

**Comment by fnrizzi** [comment]
yeah i will work out a solution, just discussed with Eric along those lines. 
we have a single shifter class and have free functions that create the shifter 
```
shifter = create_firstvec_shifter_from(matrix)
shifter = create_average_shifter_from(matrix)
shifter = create_constant_shifter(value)
etc 
```
Something like this with names TBD.
@jtencer comments?

**Comment by jtencer** [comment]
I'm trying to decide if having that free function layer in between the user and the constructor adds enough in terms of readability to be worth it.  I guess it doesn't hurt to have the option and if a user prefers the other way, there's nothing stopping them from using the constructor directly.

**Comment by pjb236** [comment]
I think the free functions for the shifter make sense, I think it actually helps with code readability.

**Comment by jtencer** [comment]
I'm ok with the free function factory approach if everyone else likes it.

**Comment by fnrizzi** [comment]
i think we should NOT let users have visiblity of the shifter concrete class. 
The user should only interact with the free funtions to create a shifter.

**Comment by jtencer** [comment]
`_` time!

**Comment by cwschilly** [comment]
@eparish1 @fnrizzi 

I've noticed that the firstVec shifter changes the shape of the input matrix, which is different behavior from the other shifters.

For example, the test for the firstvec shifter includes this assert:
```python
assert(my_snapshots_shifted.shape[2] == my_snapshots.shape[2] - 1)
```

While the other shifters include this:
```python
assert(my_snapshots_shifted.shape[2] == my_snapshots.shape[2])
```

---

 The source code (old API) for the firstvec shifter is:

```python
return my_array[:, :, 1::]-shift_vector[:, :, None]
```
While every other shifter returns:

```python
return my_array-shift_vector[:, :, None]
```

---

My question is: should I recreate this in the single Shifter class that I'm writing now, which takes in a vector generated by the free functions? For example I could pass some flag to the class in the case of the firstvec shifter that would allow for a different output.

**Comment by eparish1** [comment]
@cwschilly Thanks, this is a really good thing to bring up. 

@jtencer @fnrizzi @pjb236 What are your thoughts on this? The reason we drop the first vector is that it will all be zeros, in which case the basis will be rank deficient if we do, e.g., a dictionary. My thought would be to have all the shifters just return the full matrix (i.e., S -= shift), and then somehow keep track of if we used a first vec shifter when creating the basis and act accordingly. What do you all think?

**Comment by jtencer** [comment]
I think we should leave the vector of zeros in there and have some logic downstream that identifies if there is such a vector because it's possible to get into that situation with other shifters as well, just not as frequently.

**Comment by fnrizzi** [comment]
I strongly vote for NOT modifying the original data in any way because the shifter should only shift. 
if we want to handle the rank deficiency or some other "hidden" things in the same function/class, then we need to change the name.

**Review by fnrizzi — CHANGES_REQUESTED** [review]
this does not have the modifications about the free functions mentioned in the comments

**Comment by eparish1** [comment]
@fnrizzi I agree that the shifter should only shift.

**Comment by cwschilly** [comment]
@fnrizzi @eparish1

Is this latest commit on the right track?

Also, the main changes--1) acting in place on the snapshots and 2) using the free functions--make it act very differently from the other utils. Would we want to extend these changes to the other utils at some point?

This is in draft still since some tests are still failing (`test_trial_space_from_pod` and `test_trial_space_from_scaled_pod`).

**Comment by eparish1** [comment]
@cwschilly @fnrizzi  This looks great and is 99% there. The only change I see is that the shifts should act on an input argument rather than a class object. Currently we have:

```
    def apply_shift(self):
        self.__my_array -= self.__shift_vector[..., None]

    def apply_inverse_shift(self):
        self.__my_array += self.__shift_vector[..., None]
```

Let's make these functions act in place on an input tensor, so:

```
    def apply_shift(self, arbitrary_tensor: np.ndarray):
        arbitrary_tensor -= self.__shift_vector[..., None]

    def apply_inverse_shift(self, arbitrary_tensor: np.ndarray):
        arbitrary_tensor += self.__shift_vector[..., None]
```

I think we then don't need my_array to be a member of shifter, just the shift vector.

**Review by fnrizzi — APPROVED** [review]

**Pull request merged**
