### PR TITLE
resolve ariatools errors re directory behavior

### PR DESCRIPTION
**Pull request by jtencer**
Some of the recent changes broke regression tests on the aria side.  These changes were necessary to resolve those issues.

### CODE REVIEW

**Comment by eparish1** [comment]
@jtencer I'm fine with this; did you find the base directory useful for your stuff? Alternatively you could put the base directory into your prefix string. I got rid of it in the revision because I felt it was a little confusing to have the extra directory floating around and Patrick and Francesco mostly agreed, but I don't have strong feelings on this so am glad to keep it.

**Comment by jtencer** [comment]
The problem I ran into was that it was hardwired to use the current working directory and I needed a way to pass in a location.  If there's a different way to handle that I'd be open to it.

**Comment by eparish1** [comment]
You can do, e.g.,  "run_directory_prefix = path_to_work/run_", and it will then put everything in "path_to_work". Do you like this, or do you prefer the base_dir concept?

**Comment by jtencer** [comment]
I think I might prefer having only one argument but need it to support absolute paths. This change didn't introduce the base directory stuff. It just exposed it so that it could be something other than cwd. 

I can push a change tomorrow morning that rips out all the base directory stuff.

**Comment by jtencer** [comment]
I got rid of it in sampling.  There are still references to base_directory in `sampling_coupler_base.py` and the greedy stuff but I'm guessing those will probably go away as we propagate the Model concept through.

**Review by eparish1 — APPROVED** [review]
Looks good to me!

**Pull request merged**
