### PR TITLE
Issue96and130

### PR DESCRIPTION
**Pull request by ekrathSNL**
Fixes to issues 96 and 130. Minus the rebase commits, all changes are done in truncater.py, romtools/__init__.py, and romtools/workflows/__init__.py.

### CODE REVIEW

**Review by fnrizzi — CHANGES_REQUESTED** [review]
can you please rebase all this and fix all conflicts?

**Comment by ekrathSNL** [comment]
I rebased with develop.

**Comment by fnrizzi** [comment]
> I rebased with develop.

does not look like it, it still shows 34 files changed

**Comment by ekrathSNL** [comment]
> > I rebased with develop.
> 
> does not look like it, it still shows 34 files changed

Finally fixed it!

**Comment by fnrizzi** [comment]
@ekrathSNL the CI is failing, can you please fix it? 
https://github.com/Pressio/rom-tools-and-workflows/actions/runs/7993478483/job/21829392031?pr=155

this is the error we get:
```
************* Module romtools.workflows
romtools/workflows/__init__.py:54:0: E0401: Unable to import 'workflows.dakota' (import-error)
romtools/workflows/__init__.py:55:0: E0401: Unable to import 'workflows.greedy' (import-error)
romtools/workflows/__init__.py:56:0: E0401: Unable to import 'workflows.sampling' (import-error)
************* Module romtools.workflows.greedy.run_greedy
```

**Comment by ekrathSNL** [comment]
> @ekrathSNL the CI is failing, can you please fix it? https://github.com/Pressio/rom-tools-and-workflows/actions/runs/7993478483/job/21829392031?pr=155
> 
> this is the error we get:
> 
> ```
> ************* Module romtools.workflows
> romtools/workflows/__init__.py:54:0: E0401: Unable to import 'workflows.dakota' (import-error)
> romtools/workflows/__init__.py:55:0: E0401: Unable to import 'workflows.greedy' (import-error)
> romtools/workflows/__init__.py:56:0: E0401: Unable to import 'workflows.sampling' (import-error)
> ************* Module romtools.workflows.greedy.run_greedy
> ```

Fixed it!

**Review by fnrizzi — APPROVED** [review]

**Pull request merged**
