### PR TITLE
81 small ecsw improvements

### PR DESCRIPTION
**Pull request by pjb236**
This pull request contains many of the improvements suggested in issue 81: 

- Updated the documentation for inputs/outputs to conform to the rest of the code
- More expressive variable names
- weights are returned in an array corresponding to the sample mesh size, rather than the full mesh size
- sample mesh indices are now returned in a numpy array

### CODE REVIEW

**Comment by eparish1** [comment]
This looks good to me. The tests are failing for some reason though, I'm not sure why, it's something with respect to the formatting. Any guesses?

**Comment by pjb236** [comment]
Very odd, it's calling out errors outside of ecsw as well. Is it typical that failed formatting checks will error out all regression tests?

**Comment by eparish1** [comment]
@pjb236 

I am not sure why the error is being triggered. 

On another note, the ecsw test is occasionally hanging and causing the tests to fail. Looking into it, it seems to exit behavior of the algorithm isn't working quite right at times. For me, you can reproduce the hang by setting the numpy seed to 13 at the top of the test file, i.e.,:


```
import numpy as np
import pytest
from romtools.hyper_reduction import ecsw

np.random.seed(13)
@pytest.mark.mpi_skip
def test_ecsw_nnls():
```

In this case we hit the break on line 214, and then get stuck in the searching loop on 192-197.

Could you:

- See if you can replicate the error on your machine?
- If so, diagnose what the problem is (e.g., is the input matrix not full rank)
- Fix the exit behavior 
- If it makes sense, this actually could be a really nice test to add to test the exit behavior when the algorithm shouldn't converge.

**Comment by jtencer** [comment]
The linter error had to do with a threshold (8.5) that we were apparently hovering near before but not below.  Merging develop back in got the quality back up to 8.85.  That number should continue to increase as we fix the few outstanding exceptions to the naming conventions.

**Comment by eparish1** [comment]
Thanks John, good to know!

**Comment by pjb236** [comment]
> @pjb236
> 
> I am not sure why the error is being triggered.
> 
> On another note, the ecsw test is occasionally hanging and causing the tests to fail. Looking into it, it seems the exit behavior of the algorithm isn't working quite right at times. For me, you can reproduce the hang by setting the numpy seed to 13 at the top of the test file, i.e.,:
> 
> ```
> import numpy as np
> import pytest
> from romtools.hyper_reduction import ecsw
> 
> np.random.seed(13)
> @pytest.mark.mpi_skip
> def test_ecsw_nnls():
> ```
> 
> In this case we hit the break on line 214, and then get stuck in the searching loop on 192-197.
> 
> Could you:
> 
> * See if you can replicate the error on your machine?
> * If so, diagnose what the problem is (e.g., is the input matrix not full rank)
> * Fix the exit behavior
> * If it makes sense, this actually could be a really nice test to add to test the exit behavior when the algorithm shouldn't converge.

I was able to replicate, diagnose and fix it. Turns out the logic in the while loop did not know how to handle the situation when the sample mesh is the same as the full mesh, as when all nodes are sampled. Not sure if we want to put in a test to explicitly exercise this very improbable corner case, let me know!

**Comment by eparish1** [comment]
@pjb236 
Great, thanks! Out of curiosity, why doesn't the tolerance criteria get met when we have the full sample mesh? Is it just because the optimizer can't find the solution to the optimization problem (e.g., all ones)?

**Comment by pjb236** [comment]
> @pjb236 Great, thanks! Out of curiosity, why doesn't the tolerance criteria get met when we have the full sample mesh? Is it just because the optimizer can't find the solution to the optimization problem (e.g., all ones)?

@eparish1  Good question. Upon further investigation, it looks like the optimizer gets stuck at a solution with weights near 1.0, ranging from 0.55 to 1.36. Guess this is a good demonstration of the potential deficiencies of this approach.

**Comment by pjb236** [comment]
Looks like things are still failing intermittently, looking into it right now.

**Comment by fnrizzi** [comment]
> Looks like things are still failing intermittently, looking into it right now.

@cwschilly can you please look at this?

**Comment by pjb236** [comment]
I think things should be ok now, found a few bugs that were causing tests to fail from time to time.

**Pull request merged**
