### PR TITLE
parallelize sampling 

### PR DESCRIPTION
**Pull request by fnrizzi**
#159 

this seems to work and i think this fits our needs, but there are caveats. 
we should try this on one of the clusters where we try to combine this with the slurm scheduler for running model evaluations 

@eparish1 @jtencer @pjb236 since you guys have used already romtoolsandworkflows with sandia codes for something, can one of you please try sometime?

### CODE REVIEW

**Comment by fnrizzi** [comment]
need to see why mpich is taking forever in the CI

**Comment by fnrizzi** [comment]
looks like mpich does not like this, generating this error:

image

**Comment by eparish1** [comment]
@fnrizzi I'll run this and let you know.

**Comment by eparish1** [comment]
@fnrizzi This wasn't working for me on a sparc test. Things run if I set the evaluation concurrency to one, but as soon as I do two nothing kicks off. We can meet to diagnose when I'm back.

**Comment by fnrizzi** [comment]
not ready until https://github.com/mpi4py/mpi4py/discussions/533 is resolved

**Comment by cwschilly** [comment]
> @fnrizzi This wasn't working for me on a sparc test. Things run if I set the evaluation concurrency to one, but as soon as I do two nothing kicks off. We can meet to diagnose when I'm back.

@fnrizzi @eparish1 I've done some more testing on this branch.

All tests pass for me locally (using an Ubuntu desktop).

On Sandia clusters, tests will only pass if I'm using MPICH (and not OpenMPI).

After building MPICH from source and installing `mpi4py`, I can run the current `test_sampling.py` as is. I can also change the existing `run_model` function so that it calls `subprocess.run(["mpirun", "-n", "4", "./mpi_main")`, where `mpi_main` is an MPI program that takes ~2 min to execute.

I used evaluation concurrencies 1, 2, and 8 and was able to verify via `htop` that the correct number of `./mpi_main` processes were running (e.g. 32 processes, when evaluation concurrency is 8).

Again, this is all on SRN clusters, only using MPICH. OpenMPI caused problems--regardless of the parallel sampling (or anything else related to `romtools`), calling `mpirun` from `subprocess.run` did not work. This was documented in [this mpi4py discussion](https://github.com/mpi4py/mpi4py/discussions/533)).

**Comment by cwschilly** [comment]
@eparish1 Have you tried running the parallel sampling via a scheduled job with `slurm`? I was only using interactive allocations.

**Comment by fnrizzi** [comment]
@eparish1 
since we know this is correct what about adding a warning message "Warning: if you are running your model using MPI via a direct call to mpirun -n ... be aware that this might or might not work for issues that are purely related to mpi. "  
and then we merge this in since it works as expected?

**Comment by fnrizzi** [comment]
@cwschilly can you please rebase this ?

**Comment by fnrizzi** [comment]
@cwschilly can you please 
(1) rebase this PR 
(2) add a warning along the lines of what i suggested above ?

**Review by eparish1 — APPROVED** [review]

**Pull request merged**
