### PR TITLE
add tests

### PR DESCRIPTION
**Pull request by jtencer**

### CODE REVIEW

**Comment by fnrizzi** [comment]
@jtencer what is going on here? what is this PR about?

**Comment by jtencer** [comment]
Tests for the outputter stuff.  They didn't have test coverage at all previously.

**Comment by fnrizzi** [comment]
> Tests for the outputter stuff. They didn't have test coverage at all previously.

so why is this touching a bunch of other files too? non related to outputter?

**Comment by jtencer** [comment]
Those are all white space changes because the formatting in vector space utils was super inconsistent.

**Review by fnrizzi — APPROVED** [review]

**Pull request merged**
