### PR TITLE
trial space: improve flow and some doc details, make `utils` a submodule

### PR DESCRIPTION
**Pull request by fnrizzi**
- improve main doc page for trial space 
- make utils a submodule of trial space (this is more consistent with what we have in other modules)

| OLD | NEW |
| ---- | ----- |
| image | image |
| image  | image |

similarly for the other concrete classes

### CODE REVIEW

**Comment by fnrizzi** [comment]
related #111 #110

**Comment by eparish1** [comment]
Thanks! This is nice. I'm good with this!

**Review by eparish1 — APPROVED** [review]
Very nice!

**Comment by eparish1** [comment]
@fnrizzi @jtencer are you good if I merge?

**Comment by fnrizzi** [comment]
I am !

**Comment by jtencer** [comment]
Do we want to roll the renaming of "trialspace" into this or do that separately/later and know that that change will also need to touch the docs?

**Comment by jtencer** [comment]
I'm totally fine with doing that later and merging this in now, just want to bring it up.

**Comment by eparish1** [comment]
We will do that separately. I just created a separate issue for it.

**Pull request merged**
