### PR TITLE
create basic protocol implementation as starting point

### LINKED ISSUE #156: Add "model" class
We will add a "model" class that encapsulates information for setting up and running a model.

### PR DESCRIPTION
**Pull request by jtencer**

### CODE REVIEW

**Comment by eparish1** [comment]
@jtencer I'd like to change the "setup_run_directory" to "populate_run_directory", and further not pass the directory name but instead the parameter values. My thinking is that we will be responsible for making the directories, and the user only needs to populate them. What do you think?

```
class Model(Protocol):
    '''
    Partially explicit implementation
    '''          
    def __init__(self) -> None:
        '''      
        Initialize coupler
        '''
        pass
    
    def populate_run_directory(self, parameter_sample: dict) -> None:
        '''
        This function populates a run directory.
        Examples would be setuping up input files, linking mesh files.
        '''
        pass                               

    def run_model(self, parameter_sample: dict) -> int:
        '''
        This function is called from a run directory. It needs to execute our
        model.  If the model runs succesfully, return 0.  If fails, return 1.
        '''
        pass
        


```

**Comment by eparish1** [comment]
@jtencer @pjb236 @fnrizzi @ekrathSNL 

Do we want run_model() to return a qoi value? Alternatively, we will have another model template for, e.g., greedy which has a "return_qoi" function.

**Comment by pjb236** [comment]
@eparish1 I'm leaning toward a return_qoi function.

**Comment by eparish1** [comment]
@fnrizzi @jtencer @pjb236 @ekrathSNL 

Any opinions about these protocols for our models:


```
class Model(Protocol):
    '''
    Baseline model protocol 
    '''
    def __init__(self) -> None:
        '''
        Initialize coupler
        '''
        pass

    def populate_run_directory(self, parameter_sample: dict) -> None:
        '''
        This function populates a run directory.
        Examples would be setuping up input files, linking mesh files.
        '''
        pass

    def run_model(self, parameter_sample: dict) -> int:
        '''
        This function is called from a run directory. It needs to execute our
        model.  If the model runs succesfully, return 0.  If fails, return 1.
        '''
        pass



class QoiModel(Model,Protocol):
    '''
    Protocol for a model that has a return_qoi implementation
    '''

    def return_qoi(self, parameter_sample: dict) -> np.ndarray:
        '''
        This function is called from a run directory
        AFTER run_model has been run
        '''
        pass


class QoiModelWithErrorEstimate(QoiModel,Protocol):
    '''
    Protocol for a model that has a return_qoi and compute_error_estimate
    '''
    
    def compute_error_estimate(self, parameter_sample: dict) -> np.ndarray:
        '''
        This function is called from a run directory
        AFTER run_model has been run
        '''
        pass


```

**Comment by ekrathSNL** [comment]
Is populate_run_directory being called inside the run_directory?

**Comment by eparish1** [comment]
@ekrathSNL  yes, I'll add that to the description.

**Comment by jtencer** [comment]
So there's an external process that `cd`s to that location before calling that function?

I think I prefer passing in a location and then having `populate_run_directory` either copy/link stuff into the location without changing the current directory or changing the directory but then changing it back.  Otherwise, the directory from which you call it becomes an undocumented part of the interface.

**Comment by pjb236** [comment]
Passing a parameter dictionary to return_qoi and compute_error_estimate assumes that the name of the directories is encoded in that dictionary some how. Given that these are supposed to be called AFTER run_model, I think it might make sense to pass a path instead, like John suggested. This would also give me exactly what I need for the residual evaluator, and for workflows that do post processing on hyper-reduced ROMs.

**Comment by jtencer** [comment]
I have another project where I got bitten pretty hard recently for implicitly assuming something about the current directory.  Because pytest will continue running tests after a failure, you can have one failure that gets the current directory state out of whack and then a cascade of other test failures due to that state being wrong that mask the root problem.  I'd like to try to avoid going through that again if possible by (1) avoiding depending on the current directory if at all possible and (2) using the `cwd` argument for `subprocess.run` or `try/finally` blocks to wrap calls to external programs if those external programs need to be run from a particular location.

**Comment by eparish1** [comment]
I'm fine with having a directory be passed, and the user is responsible for cd'ing to it if they so need to. But what do you all think about run_model, get_qoi, and get_error estimate? Should this also have a directory be passed? IMO, they should all follow the same pattern so I think it would be best if they all have a directory get passed, and then the user is responsible for cd'ing to it.

**Comment by pjb236** [comment]
I'm fine with passing a directory and the parameters to all of them. The user can decide which of the two to use.

**Comment by jtencer** [comment]
What's the use-case for needing the parameters dict for those functions?

**Comment by eparish1** [comment]
I think we can eliminate them; I don't think there is an obvious use case.

Do you all like the "return_qoi" idea vs having, say, a "run_model_and_return_qoi()"?

**Comment by pjb236** [comment]
I think having both could be useful. I could see situations in which you want to go back and evaluate a QoI that wasn't computed initially.

**Comment by jtencer** [comment]
Yeah.  I like having them be separate.  I might could go for `get_qoi` or `compute_qoi` rather than `return_qoi` but don't feel very strongly about it.

Do we want to split it up into 3 protocols or throw it all into 1?

**Comment by eparish1** [comment]
I like the multiple protocols, because, e.g., the sampler only needs the first one.  I think it will be unclear what is needed if we put them all into one.

**Comment by eparish1** [comment]
Also, @jtencer, thinking on it more, II want to pass the parameter sample to the "run_model" for the use case where we don't rely on any input scripts and run_model is, e.g., just calling a python function. As far as passing it to the qoi and error estimate, a use case I can think of is if the parameters are need to compute the QoI and/or error estimate.

**Comment by jtencer** [comment]
Would there be any value in having an object that has a `Model`, a parameter dict, and a folder name and then that's the thing that the workflows use?

**Comment by eparish1** [comment]
So an updated protocol for the baseline model looks like this. Any thoughts on if the run_directory be an absolute path, or path relative to the base? 


```
class Model(Protocol):
    '''          
    Baseline model protocol 
    '''          
    def __init__(self) -> None:
        '''
        Initialize coupler
        '''
        pass
    
    def populate_run_directory(self, run_directory: str, parameter_sample: dict) -> None:
        '''
        This function is called from the base directory and is 
        responsible for populating the run directory located at run_directory 
        
        Examples would be setuping up input files, linking mesh files.

        Args:
          run_directory (str): Absolute path to run_directory.
          parameter_sample: Dictionary contatining parameter names and sample values

        '''
        pass
    
    def run_model(self, run_directory: str, parameter_sample: dict) -> int:
        '''
        This function is called from the base directory. It needs to execute our
        model.  If the model runs succesfully, return 0.  If fails, return 1.

        Args:
          run_directory (str): Absolute path to run_directory.
          parameter_sample: Dictionary contatining parameter names and sample values

        '''
        pass
```

**Comment by eparish1** [comment]
@jtencer  "Would there be any value in having an object that has a Model, a parameter dict, and a folder name and then that's the thing that the workflows use?"

Glad to explore this more, but I don't think so. I think this just adds an extra layer. In some sense I feel like this is what the Couplers are now, and the interplay between a common parameter space and different models will get confusing I believe.

**Comment by ekrathSNL** [comment]
My preference would be an absolute path.

If we're passing a directory, we might also want to have the option to pass a baseline directory where files to be copied or linked are stored and the main directory where everything is contained.

**Comment by jtencer** [comment]
I think that the baseline directory or template directory probably counts as an implementation detail for `populate_run_directory` because maybe you have those files somewhere but maybe you just produce them whole cloth inside of that function.

So your implementation of `Model` could include that, but it isn't required by anything using `Model` downstream so it isn't part of the protocol.

**Comment by fnrizzi** [comment]
> So an updated protocol for the baseline model looks like this. Any thoughts on if the run_directory be an absolute path, or path relative to the base?
> 

i vote for absolute path

**Comment by eparish1** [comment]
@jtencer I can't request a final review since you created the PR. Can you review what I just pushed?

**Comment by jtencer** [comment]
I'm not allowed to approve it either (since I pushed to it probably?)  It'll have to be @fnrizzi  or @pjb236 so I guess that means we need to be careful not to all push to the same merge request...

I did just notice that the merge request includes both a `Model` protocol and a `ApplicationCoupler` protocol that seem to be pretty much the same thing.  It looks like `Model` is the one with all the updates but we might should talk about the name and if we want to use something less vague than "model"

**Comment by eparish1** [comment]
@jtencer Good catch, I missed the push on removing the application coupler. 

I like "Model" more than application coupler, but am glad to go with other thoughts.

**Comment by jtencer** [comment]
What about `Simulator`?  I feel like "model" gets really overloaded, but I suppose it is consistent with "FOM" and "ROM" so maybe `Model` is best.

**Comment by fnrizzi** [comment]
I like either model or evaluator

**Comment by jtencer** [comment]
Unless @pjb236 objects, I'm good with `Model` then

**Comment by eparish1** [comment]
I vote for model. Simulator and Evaluator feel more ambiguous to me.

**Review by pjb236 — APPROVED** [review]
Looks good to me

**Pull request merged**
